### ISSUE TITLE
zos_fetch task fails if system sends a prelogin message

### ISSUE THREAD

**Issue by torinreilly** [ansible-collections/ibm_zos_core#150]
##### SUMMARY
Some of our systems present a message prior to login, often to identify the system or its use. For example:
```
!:~/ $ ssh example@example.com
  ***************************************************************************
  *  Welcome to systemX. WARNING: this is a live production system, etc  *
  ***************************************************************************
example@example.com's password: 
```
When using the zos_fetch module this prelogin message seems to be redirected to stderr. This causes the Ansible task to fail despite successfully transferring the file to the control node:
```
fatal: [example.com]: FAILED! => {
    "changed": false,
    "msg": "Error transferring remote data from z/OS system",
    "rc": 0,
    "stderr": "  ***************************************************************************
  *  Welcome to systemX. WARNING: this is a live production system, etc  *
  *************************************************************************** "
}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zos_fetch (potentially zos_copy as well?)

##### ANSIBLE VERSION
```
ansible 2.9.4
  config file = /Users/treilly@us.ibm.com/../ansible/ansible.cfg
  configured module search path = ['/Users/../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.4_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Dec 27 2019, 18:05:45) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/../ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Target OS: z/OS V2R4
ZOAU: 1.0.3

##### STEPS TO REPRODUCE

On a system with a prelogin message
```
- hosts: all
  collections:
  - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  tasks:
  - name: Fetch the dataset member
    zos_fetch:
      src: "ANY.DSN(MEMBER)"
      dest: "/tmp/output.txt"
```

##### EXPECTED RESULTS
```
TASK [Fetch the dataset member] *******************************************************
changed: [example.com] => {"changed": true, "data_set_type": "Partitioned", "dest": "/tmp/output.txt", "file": "ANY.DSN(MEMBER)", "is_binary": false}
```

##### ACTUAL RESULTS
```
fatal: [example.com]: FAILED! => {
    "changed": false,
    "msg": "Error transferring remote data from z/OS system",
    "rc": 0,
    "stderr": "  ***************************************************************************
  *  Welcome to systemX. WARNING: this is a live production system, etc  *
  *************************************************************************** "
}
```

**Comment by asifmahmud** [comment]
Thank you @torinreilly for opening this issue. To add context to the problem, Torin's system has a pre-login message when a user logs in:

<img width="697" alt="Screen Shot 2020-08-04 at 1 48 23 PM" src="https://user-images.githubusercontent.com/20392124/89333911-8e354080-d64a-11ea-84f1-df8e150f46e8.png">


When SFTP is used to transfer a file to/from that system, this login message is sent to the `stderr`.

<img width="834" alt="Screen Shot 2020-08-04 at 2 10 18 PM" src="https://user-images.githubusercontent.com/20392124/89333938-9beac600-d64a-11ea-860c-07680ccc1183.png">

The fetch module interprets this as a potential transfer issue and fails as a result. The dilemma here is that we cannot ignore `stderr` altogether as that would be ignoring all other potential issues that also get redirected to `stderr`. Another characteristic of SFTP is that it could encounter an error but the return code could still be 0, as is the case here.

A potential solution would be to only consider `stderr` when return code is non-zero.

**Comment by asifmahmud** [comment]
@torinreilly , do experience this behavior for zos_copy as well?

**Comment by asifmahmud** [comment]
I have pushed an update for `zos_fetch` that allows you to override the default behavior for ftp stderr. Simply set `ignore_sftp_stderr` parameter to `true`.

Here is the branch: `update/78/ftp-ignore-stderr`

Let us know if that fixes your problem.

**Comment by torinreilly** [comment]
This seems to solve the problem. As for `zos_copy` I did experience the same behavior... After setting `ignore_sftp_stderr` to `true` for `zos_copy` that problem seems to be fixed as well. I did notice however with `ignore_sftp_stderr`, where a return code was non-zero or null, I did still see the error message, which I think is a definitely a good thing but should be made clear in documentation:
```
fatal: [example.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dest": "EXAMPLE.TEST(FILE)",
            "ignore_sftp_stderr": true,
            "src": "/tmp/test/example.com/FILE"
        }
    },
    "msg": "Failed during execution of usscmd: cp -F rec /tmp/ansible-zos-copy-payload-D200807-T111323 \"//'EXAMPLE.TEST(FILE)'\", Return code: 1; stdout: ; stderr: cp: FSUM6258 cannot open file \"//'EXAMPLE.TEST(FILE)'\": EDC5061I An error occurred when attempting to define a file to the system. (errno2=0xC00B0403)\n",
    "rc": null,
    "stderr": null,
    "stderr_lines": null,
    "stdout": null,
    "stdout_lines": null
}
```
