### ISSUE TITLE
Error while trying to execute sample playbook

### ISSUE THREAD

**Issue by gcartier94** [ansible-collections/ibm_zos_core#79]
##### SUMMARY
I've tried to execute a sample playbook using the ibm_zos_core collection and I've faced some issues.

I've received the message below while running a sample playbook:
**CEE3204S The system detected a protection exception (System Completion Code=0C4).**

Some disclaimers:
- I have Ansible 2.9.7 locally on my machine.
- My z/OS environment has ZOAU version 1.0.1
- The python version installed on z/OS is Python 3.6.1 (Rocket port)
- I'm running the playbook as my own mainframe user (I've exchanged the ssh keys for that)
- I have configured the necessary variables in group_vars folder.
- I was able to successfully run playbooks using native Ansible modules like ping on my z/OS environment.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
I've tried to execute a sample playbook using the module zos_job_submit and the module zos_job_query

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gcartier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
No output
```

##### OS / ENVIRONMENT

- z/OS 2.4
- My z/OS environment has ZOAU version 1.0.1
- The python version installed on z/OS is Python 3.6.1 (Rocket port)
- I'm running the playbook as my own mainframe user (I've exchanged the ssh keys for that)

##### STEPS TO REPRODUCE

- Created a base project directory structure very similar to the playbook examples in this repository, with an inventory file, playbook file and a group_var dir containing the environment variables to be used by the playbook

```yaml
---
- name: submit tso jcl
  hosts: lbi9
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment:
    "{{ environment_vars }}"
  tasks:
    - name: submit jcl
      zos_job_submit:
        src: A118151.TESTS.JCL(IEFBR14T)
        location: DATA_SET
```

The group_var all.yml file contain the following
```
environment_vars:
        _BPXK_AUTOCVT: ON
        ZOAU_ROOT: "/_APPS/zoau"
        PYTHONPATH: "/_APPS/zoau/lib"
        LIBPATH: "/_APPS/zoau/lib:/_APPS/rocket/python-2017-04-12-py36/python36/lib:/usr/lib:/lib:."
        PATH: "/_APPS/zoau/bin:/_APPS/rocket/python-2017-04-12-py36/python36/bin/python:/bin"
```
- Execured the following command
```
ansible-playbook -i mainframe_inventory submit-jcl.yml --user a118151 -vvv
```

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gcartier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/gcartier/dev/projects/mainframe-sle/ansible/ansible_for_mainframe/zos-submit-jcl/mainframe_inventory as it did not pass its verify_file() method
script declined parsing /home/gcartier/dev/projects/mainframe-sle/ansible/ansible_for_mainframe/zos-submit-jcl/mainframe_inventory as it did not pass its verify_file() method
auto declined parsing /home/gcartier/dev/projects/mainframe-sle/ansible/ansible_for_mainframe/zos-submit-jcl/mainframe_inventory as it did not pass its verify_file() method
Parsed /home/gcartier/dev/projects/mainframe-sle/ansible/ansible_for_mainframe/zos-submit-jcl/mainframe_inventory inventory source with ini plugin

PLAYBOOK: submit-jcl.yml ***************************************************************************************************************************************************
1 plays in submit-jcl.yml

PLAY [submit tso jcl] ******************************************************************************************************************************************************
META: ran handlers

TASK [submit jcl] **********************************************************************************************************************************************************
task path: /home/gcartier/dev/projects/mainframe-sle/ansible/ansible_for_mainframe/zos-submit-jcl/submit-jcl.yml:10
<200.142.195.216> ESTABLISH SSH CONNECTION FOR USER: a118151
<200.142.195.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="a118151"' -o ConnectTimeout=10 -o ControlPath=/home/gcartier/.ansible/cp/315f95b5b8 200.142.195.216 '/bin/sh -c '"'"'echo ~a118151 && sleep 0'"'"''
<200.142.195.216> (0, '/u/A118151\n', '')
<200.142.195.216> ESTABLISH SSH CONNECTION FOR USER: a118151
<200.142.195.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="a118151"' -o ConnectTimeout=10 -o ControlPath=/home/gcartier/.ansible/cp/315f95b5b8 200.142.195.216 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /u/A118151/.ansible/tmp `"&& mkdir /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322 && echo ansible-tmp-1588630794.22-3139-153451034877322="` echo /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322 `" ) && sleep 0'"'"''
<200.142.195.216> (0, 'ansible-tmp-1588630794.22-3139-153451034877322=/u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322\n', '')
<200.142.195.216> Attempting python interpreter discovery
<200.142.195.216> ESTABLISH SSH CONNECTION FOR USER: a118151
<200.142.195.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="a118151"' -o ConnectTimeout=10 -o ControlPath=/home/gcartier/.ansible/cp/315f95b5b8 200.142.195.216 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<200.142.195.216> (0, 'PLATFORM\nOS/390\nFOUND\n/usr/bin/python\nENDFOUND\n', '')
<200.142.195.216> Python interpreter discovery fallback (unsupported platform for extended discovery: os/390)
Using module file /home/gcartier/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py
<200.142.195.216> PUT /home/gcartier/.ansible/tmp/ansible-local-3133FJFRXn/tmpH5Dohp TO /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322/AnsiballZ_zos_job_submit.py
<200.142.195.216> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="a118151"' -o ConnectTimeout=10 -o ControlPath=/home/gcartier/.ansible/cp/315f95b5b8 '[200.142.195.216]'
<200.142.195.216> (0, 'sftp> put /home/gcartier/.ansible/tmp/ansible-local-3133FJFRXn/tmpH5Dohp /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322/AnsiballZ_zos_job_submit.py\n', '')
<200.142.195.216> ESTABLISH SSH CONNECTION FOR USER: a118151
<200.142.195.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="a118151"' -o ConnectTimeout=10 -o ControlPath=/home/gcartier/.ansible/cp/315f95b5b8 200.142.195.216 '/bin/sh -c '"'"'chmod u+x /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322/ /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322/AnsiballZ_zos_job_submit.py && sleep 0'"'"''
<200.142.195.216> (0, '', '')
<200.142.195.216> ESTABLISH SSH CONNECTION FOR USER: a118151
<200.142.195.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="a118151"' -o ConnectTimeout=10 -o ControlPath=/home/gcartier/.ansible/cp/315f95b5b8 -tt 200.142.195.216 '/bin/sh -c '"'"'_BPXK_AUTOCVT=True PYTHONPATH=/_APPS/zoau/lib PATH=/_APPS/zoau/bin:/_APPS/rocket/python-2017-04-12-py36/python36/bin/python:/bin ZOAU_ROOT=/_APPS/zoau LIBPATH=/_APPS/zoau/lib:/_APPS/rocket/python-2017-04-12-py36/python36/lib:/usr/lib:/lib:. /usr/bin/python /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322/AnsiballZ_zos_job_submit.py && sleep 0'"'"''
<200.142.195.216> (139, 'CEE3204S The system detected a protection exception (System Completion Code=0C4).\r\n         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/logging.c at entry point logger at statement 45 at compile unit offset +000000001A54FD64 at entry offset \r\n         +0000000000000224 at address 000000001A54FD64.\r\n', 'Shared connection to 200.142.195.216 closed.\r\n')
<200.142.195.216> Failed to connect to the host via ssh: Shared connection to 200.142.195.216 closed.
<200.142.195.216> ESTABLISH SSH CONNECTION FOR USER: a118151
<200.142.195.216> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="a118151"' -o ConnectTimeout=10 -o ControlPath=/home/gcartier/.ansible/cp/315f95b5b8 200.142.195.216 '/bin/sh -c '"'"'rm -f -r /u/A118151/.ansible/tmp/ansible-tmp-1588630794.22-3139-153451034877322/ > /dev/null 2>&1 && sleep 0'"'"''
<200.142.195.216> (0, '', '')
[WARNING]: Platform os/390 on host 200.142.195.216 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter
could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [200.142.195.216]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 200.142.195.216 closed.\r\n",
    "module_stdout": "CEE3204S The system detected a protection exception (System Completion Code=0C4).\r\n         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/logging.c at entry point logger at statement 45 at compile unit offset +000000001A54FD64 at entry offset \r\n         +0000000000000224 at address 000000001A54FD64.\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 139
}

PLAY RECAP *****************************************************************************************************************************************************************
200.142.195.216            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by blakeinate** [comment]
Hi @gcartier94 , this error appears to be coming from ZOAU,  do you happen to know which build of ZOAU 1.0.1 you are using? I will try to reproduce your issue.

We have seen similar errors when running particular versions of ZOAU, the latest collection updates in the dev branch of this repo should fix the issues we have encountered. If I am unable to reproduce your issue, it may be worth building from the latest source. [You can find  info on building from source here](https://ansible-collections.github.io/ibm_zos_core/installation.html#local-build)

**Comment by gcartier94** [comment]
Hi @blakeinate , thank you for the quick response!

The output from ZOAU .buildinfo:
```
$ cat .buildinfo
# Generated File. Do Not Edit
build: 2019/12/10 15:09:58 CUT V1.0.1
```

**Comment by blakeinate** [comment]
Hi @gcartier94, using the same build of ZOAU, version 1.0.0 of our collection, and the same set of environment variables, I was unable to reproduce the problem.

However, I have definitely encountered the same or a very similar issue before. I believe it is related to a particular command in ZOAU which can sometimes return incorrectly encoded responses.

I am attaching a copy of the latest development build, changes have been made since 1.0.0 to address the errors I have experienced. You can install with ` ansible-galaxy collection install ibm-ibm_zos_core-1.1.0-beta1.tar.gz`

Please let me know if the fixes resolve your issue, if not, I will continue investigating to ensure the problem is resolved in our upcoming release.

[ibm-ibm_zos_core-1.1.0-beta1.tar.gz](https://github.com/ansible-collections/ibm_zos_core/files/4581443/ibm-ibm_zos_core-1.1.0-beta1.tar.gz)

**Comment by gcartier94** [comment]
Thanks @blakeinate! I will test this development build and get back with results soon.

**Comment by gcartier94** [comment]
@blakeinate 
I've tested the same playbook again using the development build you provided. Unfortunately the issue remains.

These are the steps I've followed:

- Forced the replacement of the ibm_z_core collection using the following command:
```
ansible-galaxy collection install ibm-ibm_zos_core-1.1.0-beta1.tar.gz --force
```
- Re-executed the same playbook with the command 
```
ansible-playbook -i mainframe_inventory submit-jcl.yml --user a118151
```

The result was the following:
```
PLAY [submit tso jcl] **************************************************************************************************

TASK [submit jcl] ******************************************************************************************************
[WARNING]: Platform os/390 on host 200.142.195.216 is using the discovered Python interpreter at /usr/bin/python, but
future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [200.142.195.216]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "CEE3204S The system detected a protection exception (System Completion Code=0C4).\n         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/logging.c at entry point logger at statement 45 at compile unit offset +000000001A54FD64 at entry offset \n         +0000000000000224 at address 000000001A54FD64.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 139}
```

**Comment by blakeinate** [comment]
Hi @gcartier94 ,

I'm sorry to hear that the latest build did not fix your problem. We can try a few other things:

First, I notice that the python interpreter at /usr/bin/python is being selected, would it be possible for you to set the variable
```
ansible_python_interpreter: /_APPS/rocket/python-2017-04-12-py36/python36/bin/python
```
 in your inventory file?

Example inventory:
```yaml
zsystem:
  hosts:
    ecxxxxxx:
      ansible_host: ecxxxxxx.ibm.com
      ansible_user: omvsadm
      ansible_python_interpreter: /_APPS/rocket/python-2017-04-12-py36/python36/bin/python
```

**Comment by gcartier94** [comment]
The SC04 abend continues, but the warning message about the python version on /usr/bin/python disappeared.
```
ansible-playbook -i mainframe_inventory submit-jcl.yml 

PLAY [submit tso jcl] ********************************************************************************************

TASK [submit jcl] ************************************************************************************************
fatal: [lbi9]: FAILED! => {"changed": false, "module_stderr": "CEE3204S The system detected a protection exception (System Completion Code=0C4).\n         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/logging.c at entry point logger at statement 45 at compile unit offset +000000001A54FD64 at entry offset \n         +0000000000000224 at address 000000001A54FD64.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 139}

PLAY RECAP *******************************************************************************************************
lbi9                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by settti** [comment]
Hello, I am getting the exact same error when trying the zos-collection-sample-v2.yaml. All tasks are ok until "Create a PDS data set xxx.SOME.DATA.SET".   Using ZOAU Python API for datasets in a custom python script works fine in z/OS USS.
I also had to include following environments variables in ansible group vars for other tasks to work:
```
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_OUT: "txt"
```
Target host:
- z/OS V2R3
- Rocket port of Python 3.6.1
- SMP/E installed ZOAU 1.0.2

Control node:
- ibm_zos_core 1.1.0-beta1
- ansible 2.9.6

```
(139, b'', b'CEE3204S The system detected a protection exception (System Completion Code=0C4).\n         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/Datasets.c at entry point datasets_create at statement 145 at compile unit offset +00000000134A1F40 at entry offset \n         +00000000000001F8 at address 00000000134A1F40.\n')
<> Failed to connect to the host via ssh: CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/Datasets.c at entry point datasets_create at statement 145 at compile unit offset +00000000134A1F40 at entry offset 
         +00000000000001F8 at address 00000000134A1F40.
fatal: [zvm]: FAILED! => {
    "changed": false,
    "module_stderr": "CEE3204S The system detected a protection exception (System Completion Code=0C4).\n         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/Datasets.c at entry point datasets_create at statement 145 at compile unit offset +00000000134A1F40 at entry offset \n         +00000000000001F8 at address 00000000134A1F40.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 139
}
```

**Comment by blakeinate** [comment]
I appreciate your input @settti , we have had multiple issues with ZOAU >= 1.0.2 and Ansible. We are trying to work through these errors with the ZOAU team and hope to have additional information soon. In all cases, the code works fine when run from a python script in USS, making this issue very hard to debug. 

As a workaround, ZOAU 1.0.1 PTF2 can be used with very few issues.

**Comment by blakeinate** [comment]
@gcartier94 any progress on your end?

**Comment by gcartier94** [comment]
@blakeinate , we still didn't had a chance to change and test the ZOAU 1.0.1 PTF2. Hopefully, we'll be able to test it next week.

**Comment by settti** [comment]
Is there any chance to get ZOAU via regular web download? To get ZOAU 1.0.2 over ibm shopz took us over a month.

**Comment by blakeinate** [comment]
@settti I have a playbook that will deploy ZOAU from artifactory as long as you have access to IBM intranet. Are you an IBM employee? If so, send me a slack message at *blake.becker* and I will get things in motion for you. 

Hopefully the artifactory deployment playbook will be publicly available in the near future, although it won't directly provide much benefit without access to IBM intranet.

**Comment by settti** [comment]
@blakeinate Thanks but I am not an ibm employee. We are a regular ibm customer.

**Comment by blakeinate** [comment]
@settti I will try to find a fast path for you; I appreciate your patience.

**Comment by blakeinate** [comment]
@settti can you reach out to me via email? blake.becker@ibm.com

**Comment by gcartier94** [comment]
Hi @blakeinate I was able to get the PTF2 build from ZOAU. Unfortunately, I'm still getting the same errors.

My group_vars/all.yml looks like this now:
```YAML
environment_vars:
        _BPXK_AUTOCVT: ON
        ZOAU_HOME: "/u/A118151/zoau"
        ZOAU_ROOT: "/u/A118151/zoau"
        PYTHONPATH: "/u/A118151/zoau/lib"
        LIBPATH: "/u/A118151/zoau/lib:/_APPS/rocket/python-2017-04-12-py36/python36/lib:/usr/lib:/lib:."
        PATH: "/u/A118151/zoau/bin:/_APPS/rocket/python-2017-04-12-py36/python36/bin/python:/bin"
```

The playbook I'm trying to run:
```YAML
---
- name: submit tso jcl
  hosts: lbi9
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment:
    "{{ environment_vars }}"
  tasks:
    - name: submit jcl
      zos_job_submit:
        src: A118151.TESTS.JCL(IEFBR14T)
        location: DATA_SET
```

On USS this is the result of the `ls -R` command on `/u/A118151/zoau`:
```
$ ls -R

.:
bin             docs            lib
conf            include         zoau-1.0.1.pax

./bin:
dcp         dls         dtail       llwhence    mvstmp      pparm
dcpraw      dlsraw      dtouch      mls         opercmd     pproc
ddiff       dmv         dwhence     mmv         parmgrep    procgrep
ddls        drm         hlq         mrm         parmwhence  procwhence
decho       drmraw      jcan        mvscmd      pcon        zoaversion
dgrep       dsed        jls         mvscmdauth  pjdd
dinfo       dsfilter    jsub        mvscmdmsg   pll

./conf:
log4j2.properties

./docs:
C                         zoautil-java-javadoc.zip

./docs/C:
cat1              drm-msg.1         llwhence-msg.1    pcon-msg.1
dcp-msg.1         drmraw-msg.1      mls-msg.1         pjdd-msg.1
dcpraw-msg.1      dsed-msg.1        mmv-msg.1         pll-msg.1
ddiff-msg.1       dsfilter-msg.1    mrm-msg.1         pparm-msg.1
ddls-msg.1        dtail-msg.1       mvscmd-msg.1      pproc-msg.1
decho-msg.1       dtouch-msg.1      mvscmdauth-msg.1  procgrep-msg.1
dgrep-msg.1       dwhence-msg.1     mvscmdmsg-msg.1   procwhence-msg.1
dinfo-msg.1       hlq-msg.1         mvstmp-msg.1      zoaversion-msg.1
dls-msg.1         jcan-msg.1        opercmd-msg.1
dlsraw-msg.1      jls-msg.1         parmgrep-msg.1
dmv-msg.1         jsub-msg.1        parmwhence-msg.1

./docs/C/cat1:
dcp.1         dlsraw.1      dwhence.1     mrm.1         pcon.1
dcpraw.1      dmv.1         hlq.1         mvscmd.1      pjdd.1
ddiff.1       drm.1         jcan.1        mvscmdauth.1  pll.1
ddls.1        drmraw.1      jls.1         mvscmdmsg.1   pparm.1
decho.1       dsed.1        jsub.1        mvstmp.1      pproc.1
dgrep.1       dsfilter.1    llwhence.1    opercmd.1     procgrep.1
dinfo.1       dtail.1       mls.1         parmgrep.1    procwhence.1
dls.1         dtouch.1      mmv.1         parmwhence.1  zoaversion.1

./include:
vector.h   zoautil.h

./lib:
com.ibm.zoautil_1.0.1.jar  log4j-core-2.12.1.jar      zoautil_py
libZOAU_JNI64.so           zoautil.so
log4j-api-2.12.1.jar       zoautil.x

./lib/zoautil_py:
Datasets.so      OperatorCmd.py   _OperatorCmd.so  __pycache__
Jobs.py          ZSystem.py       _ZSystem.so      types.so
MVSCmd.so        _Jobs.so         __init__.py

./lib/zoautil_py/__pycache__:
Jobs.cpython-36.pyc         ZSystem.cpython-36.pyc
OperatorCmd.cpython-36.pyc  __init__.cpython-36.pyc
```

This is the build info:
```
$ cat bin/.buildinfo
# Generated File. Do Not Edit
build: 2020/01/20 22:38:49 CUT V1.0.1
```

This is the results I get while running the playbook:
```
ansible-playbook -i mainframe_inventory submit-jcl.yml

PLAY [submit tso jcl] ******************************************************************************************************************************************************

TASK [submit jcl] **********************************************************************************************************************************************************
fatal: [lbi9]: FAILED! => {"changed": false, "module_stderr": "CEE3204S The system detected a protection exception (System Completion Code=0C4).\n         From compile unit TVT6031:/u/dbbAutomation/zoau/workspace/ZOAU-Pipelines/mvsutil-python-buildTest/build/mvsutil-python/src/logging.c at entry point logger at statement 45 at compile unit offset +000000001A54FD64 at entry offset \n         +0000000000000224 at address 000000001A54FD64.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 139}

PLAY RECAP *****************************************************************************************************************************************************************
lbi9                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by drbruce-git** [comment]
@settti There is currently no web download for ZOAU though we will investigate providing one in the future.  We can provide you with a pax file for ZOAU v1.0.1 PTF2 that would be for setting up a test environment only since it would not be an SMP/E installation package. Let me know if that is acceptable.  I am in contact with @blakeinate and can send you the file via email.

**Comment by settti** [comment]
@drbruce-git Thanks for your respone. I’ve sent you an email.

**Comment by settti** [comment]
We have downgraded our ZOAU version to 1.0.1 (bash-4.3$ zoaversion    
2019/12/10 15:09:58 CUT) and now sample v2 playbook runs successfully. BUT only when following env variables are added in group vars:
  _TAG_REDIR_IN: "TXT"
  _TAG_REDIR_ERR: "TXT"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_OUT: "TXT"

**Comment by ddimatos** [comment]
@settti thanks for the update, in our next release there will be documentation stating our position on using `bash`, for now our position is that it won't be supported until we can alter our pipeline to include the added shell. That said, we did encounter some issues with how `bash` dealt with encodings during redirects , particularly in 4.3 and our sample v2 because that sample creates a script with a redirect and thus we needed to add in addition to your noted environment variables:
```
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
```
I needed to add:
```
LANG: "C"
_ENCODE_FILE_NEW: "IBM-1047"
_ENCODE_FILE_EXISTING: "IBM-1047"
```
And my blurb for this:
```
# - The bash shell is unsupported, if that is the only shell available, you will
#   need to control how new and existing files are tagged and encoded; an
#   example of what is needed in addition to this files environment varialbes,
#   are both "_ENCODE_FILE_NEW" and "_ENCODE_FILE_EXISTING"; for example,
#      _ENCODE_FILE_NEW: "IBM-1047"
#      _ENCODE_FILE_EXISTING: "IBM-1047"
#   Please review the README.ZOS guide included with the ported ``bash`` shell
#   for further configurations.
```

**Comment by ddimatos** [comment]
@settti This issue seems resolved can we close it now?

**Comment by blakeinate** [comment]
@ddimatos I think the initial issue was opened by @gcartier94, don't think we should close yet. Are you still experiencing issues @gcartier94 ?

**Comment by gcartier94** [comment]
@blakeinate yes, I'm still facing the same issue with the collection modules. The only exception is zos_job_submit, that in one of the most recent doesn't seem to rely on the ZOAU.

**Comment by blakeinate** [comment]
I think ZOAU 1.0.3 was released in the past couple weeks, it may be worth attempting to try the latest version; we have had good results compared to 1.0.2 @gcartier94

**Comment by gcartier94** [comment]
Thanks, I'll try that and get back to you soon.

**Comment by gcartier94** [comment]
Hello everyone,

I've tested with the new ZOAU-1.0.3, I'm getting a different kind of error now:


```json
{
   "changed":false,
   "module_stderr":"Shared connection to 200.142.195.216 closed.\r\n",
   "module_stdout":"  File \"/u/A118151/.ansible/tmp/ansible-tmp-1593976131.46-4448-207749812121500/AnsiballZ_command.py\", line 1\r\nSyntaxError: Non-UTF-8 code starting with '\\x83' in file /u/A118151/.ansible/tmp/ansible-tmp-1593976131.46-4448-207749812121500/AnsiballZ_command.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details\r\n",
   "msg":"MODULE FAILURE\nSee stdout/stderr for the exact error",
   "rc":1
}
```

My environment variables look like this:

```yaml

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "/_APPS/zoau-1.0.3"
  PYTHONPATH: "/_APPS/zoau-1.0.3/lib"
  LIBPATH: "/_APPS/zoau-1.0.3/lib:/_APPS/rocket/python-2017-04-12-py36/python36/lib:/usr/lib:/lib:."
  PATH: "/_APPS/zoau-1.0.3/bin:/_APPS/rocket/python-2017-04-12-py36/python36/bin/python:/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"

```

I'm using the most recent release of the ibm_zos_core collection (1.1.0)

**Comment by ddimatos** [comment]
Hey Guilherme, could we see your inventory? Looks like pipelining = True is not set. Can also see this [link](https://ansible-collections.github.io/ibm_zos_core/playbooks.html#sample-configuration-and-setup)

**Comment by gcartier94** [comment]
Hi @ddimatos, my ansible.cnfg looks like this:
```
[defaults]
forks = 25

[ssh_connection]
pipelining = True
```

But I think I was able to get it working now. While doing some other testing I was able to successfully run the playbooks. Basically what I did was to remove the variable `_CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"` and everything worked fine.

I think that this issue can be closed now, thank you and @blakeinate for all the support :)

**Comment by blakeinate** [comment]
I'm glad to hear things are working for you. Thanks for your patience as I know this has been a gradual process.

@ddimatos we may want to set aside some time this week to test _CEE_RUNOPTS with Rocket Python to ensure we don't need to provide separate environment options for various python ports.

**Comment by ddimatos** [comment]
I am very happy it’s working and thanks for your patience. 

Good point @blakeinate we will need to investigate Rocket pythons behavior with the variables we published for IBM python.

**Comment by gcartier94** [comment]
If you would like me to do any testings, I'd be glad to help!
